

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_strong_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network
  
  redis:
     image: redis:6.2
     ports:
       - "6379:6379"
     networks:
       - app-network


  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  userservice:
    image: visualgamer/userservice:latest
    build:
      context: .
      dockerfile: UrlShortener.UserService/Dockerfile
    ports:
      - "5005:80"
    depends_on:
      - sqlserver
      - rabbitmq
    networks:
      - app-network

  urlservice:
    image: visualgamer/urlservice:latest
    build:
      context: .
      dockerfile: UrlShortener.UrlService/Dockerfile
    ports:
      - "5003:80"
    depends_on:
      - sqlserver
      - rabbitmq
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    networks:
      - app-network

  apigateway:
    image: visualgamer/apigateway:latest
    build:
      context: .
      dockerfile: UrlShortener.ApiGateway/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - userservice
      - urlservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    networks:
      - app-network


networks:
  app-network:
